import type { Opportunity } from '../types';
import { analyzeAndScoreOpportunity } from '../utils/aiOpportunityAnalyzer';

type Job = { id: string | number; title: string; company: string; description?: string; url?: string; location?: string; category?: string; salary?: string; salaryMin?: number; salaryMax?: number; pub?: string; type?: string; source: string };
const timeout = 12000;
const clean = (s = '') => s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
async function json<T>(url:string):Promise<T>{ const c=new AbortController(); const t=setTimeout(()=>c.abort(),timeout); try{ const r=await fetch(url,{signal:c.signal,headers:{accept:'application/json','user-agent':'Marium-AI-Workspace/1.0'}}); if(!r.ok) throw new Error(`${r.status} ${r.statusText}`); return await r.json() as T; } finally{clearTimeout(t);} }
async function remotive(q:string):Promise<Job[]>{ const d=await json<any>(`https://remotive.com/api/remote-jobs?limit=100${q?`&search=${encodeURIComponent(q)}`:''}`); return (d.jobs||[]).map((x:any)=>({id:x.id,title:x.title,company:x.company_name,description:clean(x.description),url:x.url,location:x.candidate_required_location||'Worldwide',category:x.category,salary:x.salary,pub:x.publication_date,type:x.job_type,source:'Remotive'})); }
async function jobicy(q:string):Promise<Job[]>{ const d=await json<any>(`https://jobicy.com/api/v2/remote-jobs?count=100${q?`&tag=${encodeURIComponent(q)}`:''}`); return (d.jobs||[]).map((x:any)=>({id:x.id,title:x.jobTitle,company:x.companyName,description:clean(x.jobDescription||x.jobExcerpt),url:x.url,location:x.jobGeo||'Worldwide',category:x.jobIndustry,salaryMin:Number(x.salaryMin)||0,salaryMax:Number(x.salaryMax)||0,pub:x.pubDate,type:x.jobType,source:'Jobicy'})); }
async function remoteok(q:string):Promise<Job[]>{ const d=await json<any[]>('https://remoteok.com/api'); return (Array.isArray(d)?d:[]).filter((x:any)=>x?.id&&x?.position).filter((x:any)=>!q||`${x.position} ${x.description||''} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(q.toLowerCase())).slice(0,100).map((x:any)=>({id:x.id,title:x.position,company:x.company||'غير محدد',description:clean(x.description),url:x.url||'https://remoteok.com',location:x.location||'Worldwide',category:(x.tags||[])[0]||'Remote',salaryMin:Number(x.salary_min)||0,salaryMax:Number(x.salary_max)||0,pub:x.date,type:'remote',source:'Remote OK'})); }
function money(j:Job){ if(j.salaryMax) return j.salaryMax; if(j.salaryMin) return j.salaryMin; const m=(j.salary||'').replace(/,/g,'').match(/\$\s?(\d+(?:\.\d+)?)\s*([kK])?/); return m ? Number(m[1])*(m[2]?1000:1) : 0; }
function map(j:Job):Opportunity{ const reward=money(j); const desc=(j.description||`${j.title} — ${j.company}`).slice(0,12000); const skills=Array.from(new Set(((desc.match(/\b(react|typescript|javascript|python|java|kotlin|node\.js|aws|azure|firebase|sql|figma|seo|sales|writing|translation|customer support)\b/gi)||[]).concat(j.category?[j.category]:[])))).slice(0,8); return analyzeAndScoreOpportunity({id:String(j.id),title:j.title||'فرصة عمل عن بعد',company:j.company||'غير محدد',source:j.source,category:j.category||'عمل عن بعد',payoutValue:reward?Math.min(100,65+(reward/10000)*35):55,rawPayoutUSD:reward,reward,score:0,riskScore:0,status:'new',createdAt:j.pub?Date.parse(j.pub):Date.now(),sourceReliability:j.source==='Remotive'?85:j.source==='Jobicy'?82:78,executionDurationDays:/freelance|contract/i.test(j.type||'')?14:30,executionDurationScore:/freelance|contract/i.test(j.type||'')?92:78,descriptionClarity:desc.length>500?92:desc.length>180?82:65,antiFraudScore:88,totalScore:0,riskLevel:'Medium Risk',description:desc,verified:false,date:j.pub?j.pub.slice(0,10):new Date().toISOString().slice(0,10),location:j.location||'Worldwide',requiredSkills:skills,sourceUrl:j.url||'',applyUrl:j.url||'',jobType:j.type||'remote',salaryText:j.salary||(reward?`$${reward.toLocaleString()} USD`:'غير محدد')}); }
export async function aggregateRemoteJobs(search=''){ const rs=await Promise.allSettled([remotive(search),jobicy(search),remoteok(search)]); const jobs:Opportunity[]=[]; const sources:string[]=[]; const warnings:string[]=[]; rs.forEach((r,i)=>{const n=['Remotive','Jobicy','Remote OK'][i]; if(r.status==='fulfilled'){jobs.push(...r.value.map(map));sources.push(n);}else warnings.push(`${n}: تعذر الوصول للمصدر`);}); const seen=new Set<string>(); const unique=jobs.filter(x=>{const k=`${x.title.toLowerCase()}|${x.company.toLowerCase()}`; if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>b.totalScore-a.totalScore); return {jobs:unique,sources,warnings}; }
