workflows:
  codemagic-standalone-build:
    name: Codemagic Independent Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_ndk: 26.1.10909125
      java: 17
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "ai.albader.alromimh.com"
    triggering:
      events:
        - push
      branches:
        - main
    scripts:
      - name: Initialize Keystore and Properties
        script: |
          echo "$CM_KEYSTORE_BASE64" | base64 --decode > /tmp/upload-keystore.jks
          printf 'storePassword=%s\n' "$CM_KEYSTORE_PASSWORD" > key.properties
          printf 'keyPassword=%s\n' "$CM_KEY_PASSWORD" >> key.properties
          printf 'keyAlias=%s\n' "$CM_KEY_ALIAS" >> key.properties
          printf 'storeFile=/tmp/upload-keystore.jks\n' >> key.properties
      - name: Build Signed APK Standalone
        script: |
          ./gradlew clean assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - abuanasanam42@gmail.com
        notify:
          success: true
          failure: true
