name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        # تحديد مسار ملف build.gradle.kts ليتم فحص الكاش الخاص به بشكل صحيح
        cache-dependency-path: ALromimah23-main/build.gradle.kts

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ALromimah23-main

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ALromimah23-main

    - name: Build Debug APK
      run: ./gradlew assembleDebug
      working-directory: ALromimah23-main

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: ALromimah23-main/app/build/outputs/apk/debug/app-debug.apk
